In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel(r"C:\Users\rsant\Downloads\Renewl.xlsx")

In [3]:
df.head()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,UDAIPUR,Rajasthan,NaN,Self-employed,POL76237,travel,...,10,0.0,NaN,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,2390000,Self-employed,POL69429,Vehicle,...,10,1.0,30000,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,Uttar Pradesh,Rs 530000,HOUSEWIFE,POL16175,Health,...,6,0.0,0,1,4,1,No,AG144,2.8,Not Renewed
3,CUST00004,Neha Yadav,27,Other,Kanpur,uttar pradesh,1100000,Retired,POL41571,Travel,...,7,0.0,0,4,2,5,Yes,AG126,4.3,Not Renewed
4,CUST00001,Ayaan Singh,20,Male,Kolkata,West Bengal,NaN,Housewife,POL71993,Term,...,6,0.0,0,1,5,2,Yes,AG125,3.8,Renewed

In [4]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State',
       'Annual_Income', 'Occupation', 'Policy_ID', 'Policy_Type',
       'Premium_Amount', 'Sum_Assured', 'Policy_Start_Date',
       'Years_With_Company', 'Total_Claims', 'Claim_Amount',
       'Late_Payment_Count', 'Previous_Renewals', 'Satisfaction_Score',
       'Auto_Renewal_Enabled', 'Agent_ID', 'Agent_Rating',
       'Renewal_Status_Next_Year'],
      dtype='object')

In [5]:
df.shape

(1000, 23)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               1000 non-null   object
 1   Customer_Name             990 non-null    object
 2   Age                       972 non-null    object
 3   Gender                    1000 non-null   object
 4   City                      1000 non-null   object
 5   State                     1000 non-null   object
 6   Annual_Income             918 non-null    object
 7   Occupation                1000 non-null   object
 8   Policy_ID                 1000 non-null   object
 9   Policy_Type               1000 non-null   object
 10  Premium_Amount            933 non-null    object
 11  Sum_Assured               896 non-null    object
 12  Policy_Start_Date         943 non-null    object
 13  Years_With_Company        1000 non-null   int64
 14  Total_Claims              966 non-null    float64
 15  Claim_Amount              918 non-null    object
 16  Late_Payment_Count        1000 non-null   int64
 17  Previous_Renewals         1000 non-null   int64
 18  Satisfaction_Score        957 non-null    object
 19  Auto_Renewal_Enabled      1000 non-null   object
 20  Agent_ID                  1000 non-null   object
 21  Agent_Rating              970 non-null    float64
 22  Renewal_Status_Next_Year  955 non-null    object
dtypes: float64(2), int64(3), object(18)
memory usage: 179.8+ KB

In [7]:
df.isnull().sum()

Customer_ID                   0
Customer_Name                10
Age                          28
Gender                        0
City                          0
State                         0
Annual_Income                82
Occupation                    0
Policy_ID                     0
Policy_Type                   0
Premium_Amount               67
Sum_Assured                 104
Policy_Start_Date            57
Years_With_Company            0
Total_Claims                 34
Claim_Amount                 82
Late_Payment_Count            0
Previous_Renewals             0
Satisfaction_Score           43
Auto_Renewal_Enabled          0
Agent_ID                      0
Agent_Rating                 30
Renewal_Status_Next_Year     45
dtype: int64

In [8]:
df["Age"].dtype

dtype('O')

In [9]:
df["Age"].unique()

array([33, 54, 27, 20, 28, 31, 34, 29, 18, 60, 57, 37, nan, 61, 56, 24,
       46, 44, 48, 47, 0, 55, 40, 22, 50, 70, 63, 42, 35, 23, 67, 43, 66,
       25, 53, 38, 36, 45, 69, 19, 58, 39, 26, 65, 52, 41, 68, -5, 21, 30,
       51, 62, 59, 64, 32, 49, 150, 'thirty'], dtype=object)

In [10]:
df[df["Age"]=='thirty']=df[df["Age"]=='thirty'].replace('thirty',30)

C:\Users\rsant\AppData\Local\Temp\ipykernel_3656\2544396038.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[df["Age"]=='thirty']=df[df["Age"]=='thirty'].replace('thirty',30)

In [11]:
df.head()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,UDAIPUR,Rajasthan,NaN,Self-employed,POL76237,travel,...,10,0.0,NaN,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,2390000,Self-employed,POL69429,Vehicle,...,10,1.0,30000,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,Uttar Pradesh,Rs 530000,HOUSEWIFE,POL16175,Health,...,6,0.0,0,1,4,1,No,AG144,2.8,Not Renewed
3,CUST00004,Neha Yadav,27,Other,Kanpur,uttar pradesh,1100000,Retired,POL41571,Travel,...,7,0.0,0,4,2,5,Yes,AG126,4.3,Not Renewed
4,CUST00001,Ayaan Singh,20,Male,Kolkata,West Bengal,NaN,Housewife,POL71993,Term,...,6,0.0,0,1,5,2,Yes,AG125,3.8,Renewed

In [12]:
df["Age"].unique()

array([33, 54, 27, 20, 28, 31, 34, 29, 18, 60, 57, 37, nan, 61, 56, 24,
       46, 44, 48, 47, 0, 55, 40, 22, 50, 70, 63, 42, 35, 23, 67, 43, 66,
       25, 53, 38, 36, 45, 69, 19, 58, 39, 26, 65, 52, 41, 68, -5, 21, 30,
       51, 62, 59, 64, 32, 49, 150], dtype=object)

In [13]:
df[df["Age"]=='thirty']

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Gender, City, State, Annual_Income, Occupation, Policy_ID, Policy_Type, Premium_Amount, Sum_Assured, Policy_Start_Date, Years_With_Company, Total_Claims, Claim_Amount, Late_Payment_Count, Previous_Renewals, Satisfaction_Score, Auto_Renewal_Enabled, Agent_ID, Agent_Rating, Renewal_Status_Next_Year]
Index: []

[0 rows x 23 columns]

In [14]:
(df["Age"].isnull().sum()/len(df["Age"]) )*100

np.float64(2.8000000000000003)

In [15]:
((df.isnull().sum() / len(df)) * 100)

Customer_ID                  0.0
Customer_Name                1.0
Age                          2.8
Gender                       0.0
City                         0.0
State                        0.0
Annual_Income                8.2
Occupation                   0.0
Policy_ID                    0.0
Policy_Type                  0.0
Premium_Amount               6.7
Sum_Assured                 10.4
Policy_Start_Date            5.7
Years_With_Company           0.0
Total_Claims                 3.4
Claim_Amount                 8.2
Late_Payment_Count           0.0
Previous_Renewals            0.0
Satisfaction_Score           4.3
Auto_Renewal_Enabled         0.0
Agent_ID                     0.0
Agent_Rating                 3.0
Renewal_Status_Next_Year     4.5
dtype: float64

In [16]:
df.isnull().sum()

Customer_ID                   0
Customer_Name                10
Age                          28
Gender                        0
City                          0
State                         0
Annual_Income                82
Occupation                    0
Policy_ID                     0
Policy_Type                   0
Premium_Amount               67
Sum_Assured                 104
Policy_Start_Date            57
Years_With_Company            0
Total_Claims                 34
Claim_Amount                 82
Late_Payment_Count            0
Previous_Renewals             0
Satisfaction_Score           43
Auto_Renewal_Enabled          0
Agent_ID                      0
Agent_Rating                 30
Renewal_Status_Next_Year     45
dtype: int64

In [17]:
df = df.dropna(subset=['Age'])
df = df.dropna(subset=['Satisfaction_Score'])
df = df.dropna(subset=['Renewal_Status_Next_Year'])
df = df.dropna(subset=['Agent_Rating'])
df = df.dropna(subset=['Customer_Name']) 
df = df.dropna(subset=['Total_Claims'])

In [18]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Annual_Income               69
Occupation                   0
Policy_ID                    0
Policy_Type                  0
Premium_Amount              55
Sum_Assured                 91
Policy_Start_Date           49
Years_With_Company           0
Total_Claims                 0
Claim_Amount                67
Late_Payment_Count           0
Previous_Renewals            0
Satisfaction_Score           0
Auto_Renewal_Enabled         0
Agent_ID                     0
Agent_Rating                 0
Renewal_Status_Next_Year     0
dtype: int64

In [19]:
df["Age"]=df["Age"].astype(int)

In [20]:
df.dtypes

Customer_ID                  object
Customer_Name                object
Age                           int64
Gender                       object
City                         object
State                        object
Annual_Income                object
Occupation                   object
Policy_ID                    object
Policy_Type                  object
Premium_Amount               object
Sum_Assured                  object
Policy_Start_Date            object
Years_With_Company            int64
Total_Claims                float64
Claim_Amount                 object
Late_Payment_Count            int64
Previous_Renewals             int64
Satisfaction_Score           object
Auto_Renewal_Enabled         object
Agent_ID                     object
Agent_Rating                float64
Renewal_Status_Next_Year     object
dtype: object

In [21]:
df.head(2)

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,UDAIPUR,Rajasthan,NaN,Self-employed,POL76237,travel,...,10,0.0,NaN,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,2390000,Self-employed,POL69429,Vehicle,...,10,1.0,30000,1,3,3,Yes,AG108,3.1,Renewed

In [22]:
df["Annual_Income"].isnull().sum()

np.int64(69)

In [23]:
df["Annual_Income"].unique()

array([nan, 2390000, 'Rs 530000', 1100000, 850000, '₹2,100,000', 510000,
       2190000, 1280000, 1900000, 2380000, 350000, 1430000, 290000,
       380000, 860000, 580000, 2280000, '₹1,390,000', '₹1,330,000',
       'Rs 300000', 1640000, 2120000, 1830000, 1480000, 900000, 1950000,
       'Rs 1000000', 1240000, 1700000, 1010000, 1310000, 'Rs 2430000',
       1320000, '2,460,000', 320000, 1370000, 1560000, 1350000,
       'Rs 1100000', 1990000, 1600000, 1860000, '₹530,000', 2100000,
       1040000, '₹200,000', 970000, '₹1,350,000', 550000, 770000, 600000,
       '₹2,460,000', 2430000, 960000, 1170000, 480000, '1,780,000',
       1850000, 2220000, 1450000, 'Rs 1900000', 1150000, 2080000,
       '₹1,830,000', 2070000, 410000, '₹2,310,000', '₹180,000',
       '₹1,590,000', 'Rs 1650000', '2,060,000', 2260000, '₹1,190,000',
       880000, 1070000, 1820000, 2150000, 2160000, 1570000, 530000,
       300000, 1190000, 400000, 1360000, 1160000, 1940000, 470000, 200000,
       2170000, 1740000, '₹2,470,000', 1400000, 700000, 1960000, 590000,
       '1,040,000', 2040000, 2310000, 1660000, 1880000, 270000, 940000,
       '₹2,130,000', 1110000, '₹2,490,000', 1470000, 1760000, 2420000,
       1120000, 460000, 1920000, 1550000, 810000, 1610000, 'Rs 290000',
       330000, 2240000, '₹1,810,000', 2250000, '1,130,000', 2290000,
       1910000, 710000, 1730000, 670000, 340000, 1530000, 660000,
       'Rs 2490000', 490000, '₹480,000', 'Rs 640000', 1030000,
       '₹1,320,000', 920000, 2270000, 210000, 610000, 890000, 1250000,
       'Rs 360000', '1,890,000', 1220000, '₹570,000', 1650000, 2480000,
       1080000, 620000, 1930000, 1970000, '₹2,340,000', 1390000, 1980000,
       560000, 500000, 650000, 2130000, '1,820,000', 680000, 190000,
       2060000, 630000, 2330000, '₹930,000', 440000, 'Rs 900000',
       '₹990,000', 1770000, '₹580,000', 930000, 2010000, 1090000,
       '760,000', '₹1,610,000', '2,030,000', 'Rs 2020000', 'Rs 1390000',
       '1,790,000', 2300000, '₹1,710,000', '₹1,480,000', 1810000, 2180000,
       950000, '₹410,000', '1,920,000', '1,750,000', 220000, '₹690,000',
       '₹1,240,000', 690000, 1210000, 1720000, '1,480,000', 1890000,
       '2,290,000', 1420000, '1,230,000', 2210000, 260000, 910000,
       2110000, '₹2,190,000', 'Rs 500000', 1540000, '1,560,000',
       'Rs 2000000', 540000, 'Rs 2200000', '₹880,000', 1330000,
       '1,460,000', '2,270,000', 1050000, 1180000, 2360000, 2350000,
       2490000, 1140000, '₹1,170,000', 1260000, 1580000, 2410000,
       '1,610,000', 1750000, '1,180,000', '₹1,100,000', 2440000, 1130000,
       '₹510,000', 1780000, '₹2,180,000', 2030000, '₹230,000', '₹890,000',
       '570,000', '₹1,040,000', '₹1,900,000', 1630000, 1590000, 570000,
       1690000, 1270000, '₹1,760,000', 750000, 2470000, 'Rs 2280000',
       1800000, 2450000, 'Rs 510000', 1340000, 820000, 1620000, 310000,
       '1,650,000', 360000, '1,440,000', '₹610,000', '2,090,000',
       'Rs 590000', 2200000, 1840000, 2340000, 180000, 520000, 2230000,
       '₹2,090,000', 870000, '190,000', '₹1,380,000', 430000, '1,340,000',
       '₹2,140,000', 1870000, 1500000, 990000, '₹750,000', 790000,
       '1,550,000', 840000, 'Rs 1980000', '₹1,940,000', 1680000, 2320000,
       '₹850,000', '₹440,000', 830000, '₹360,000', 800000, 2400000,
       640000, 'Rs 380000', '1,260,000', '₹2,240,000', 230000,
       '1,630,000', 'Rs 850000', '700,000', 450000, 1440000, 780000,
       1200000, '2,190,000', '₹2,120,000', '2,410,000', 730000,
       '₹660,000', '₹730,000', '₹1,090,000', 1020000, 'Rs 790000',
       'Rs 2420000', 2090000, 'Rs 1040000', '1,930,000', 1380000,
       '2,210,000', 'Rs 1600000', '₹1,000,000', 740000, 1060000, 760000,
       390000, 2050000, 2140000, '₹1,680,000', '₹1,600,000', 1790000,
       '1,530,000', '₹1,520,000', 370000, '2,390,000', 'Rs 1640000',
       2460000, 1230000, '380,000', 240000, 'Rs 1520000', '₹2,060,000',
       'Rs 2380000', 1710000, 'Rs 250000', '₹1,180,000', 'Rs 260000',
       '1,580,000', '1,420,000', 1460000, '1,900,000', '₹390,000',
       '₹2,350,000', '1,540,000', 'Rs 1820000', 'Rs 1310000', '2,240,000',
       '₹1,510,000', 1520000, '₹1,430,000', 'Rs 1500000', 'Rs 190000',
       420000, '550,000'], dtype=object)

In [24]:
df["Annual_Income"]=df["Annual_Income"].str.replace(',',"")
df["Annual_Income"]=df["Annual_Income"].str.replace('Rs ',"")
df["Annual_Income"]=df["Annual_Income"].str.replace('₹',"")

In [25]:
df["Annual_Income"]=df["Annual_Income"].astype(float)

In [26]:
df["Annual_Income"].dtype

dtype('float64')

In [27]:
df["Annual_Income"].describe()

count    1.590000e+02
mean     1.407170e+06
std      6.596404e+05
min      1.800000e+05
25%      8.800000e+05
50%      1.480000e+06
75%      1.925000e+06
max      2.490000e+06
Name: Annual_Income, dtype: float64

In [28]:
df["Annual_Income"]=df["Annual_Income"].fillna(df["Annual_Income"].median())

In [29]:
df["Annual_Income"]=df["Annual_Income"].astype(int)

In [30]:
df["Annual_Income"].isnull().sum()

np.int64(0)

In [31]:
df["Annual_Income"].dtypes

dtype('int64')

In [32]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Annual_Income                0
Occupation                   0
Policy_ID                    0
Policy_Type                  0
Premium_Amount              55
Sum_Assured                 91
Policy_Start_Date           49
Years_With_Company           0
Total_Claims                 0
Claim_Amount                67
Late_Payment_Count           0
Previous_Renewals            0
Satisfaction_Score           0
Auto_Renewal_Enabled         0
Agent_ID                     0
Agent_Rating                 0
Renewal_Status_Next_Year     0
dtype: int64

In [33]:
df["Premium_Amount"].dtype

dtype('O')

In [34]:
df["Premium_Amount"].unique()

array([30000, 50000, 25000, '15,500', 17000, 42500, 14000, 6000, 63500,
       20500, 36000, 71500, 51000, 7000, 6500, 57000, 27000, 35500,
       '₹9,500', 59000, 21500, 46500, 69000, '₹61,500', '7,500', 45000,
       48500, 22500, 47500, 62500, '37,000', 45500, 38500, '₹69,500',
       39500, 28500, '73,500', 74000, 12000, 64500, nan, 15000, '₹57,000',
       '₹69,000', 59500, 11000, '₹34,000', 55000, '₹13,000', 37500, 42000,
       'Rs 43000', '₹12,000', 55500, '38,500', '60,500', 24000, '₹13,500',
       52500, 40000, 32500, 33000, 54000, 17500, 66500, '₹66,500', 46000,
       11500, 15500, 18500, 29500, 47000, 26000, 44000, 'Rs 36000', 36500,
       'Rs 47500', 28000, 65500, 25500, 24500, 'Rs 72000', '₹57,500',
       '50,000', '41,500', 9000, 'Rs 66000', 43500, '21,000', 'Rs 73000',
       18000, 8000, 7500, 19500, '59,000', '₹67,500', '₹20,000', 13500,
       63000, 'Rs 13000', 'Rs 63000', 38000, 31000, 23500, 20000, 71000,
       41000, '₹19,000', '₹58,000', 50500, 13000, 21000, 67500, 37000,
       '₹6,500', 52000, 39000, '17,500', 16000, '₹5,000', 31500, 23000,
       56000, '69,000', 'Rs 11500', 44500, '₹23,000', 72000, '₹21,000',
       '₹24,500', 64000, 32000, 58000, '30,000', '₹68,000', 51500, 33500,
       69500, 70000, 60000, 'Rs 71000', 26500, 68000, 16500, '₹47,500',
       'Rs 7500', 'Rs 38500', 73500, '67,000', 'Rs 37000', 30500, 10000,
       '72,000', 34000, 'Rs 62500', 40500, 'Rs 51000', '₹16,500',
       'Rs 22000', 74500, '24,500', 70500, '₹18,500', '55,500', 14500,
       5500, 'Rs 67500', 57500, '72,500', '₹68,500', 9500, 8500, 5000,
       35000, 27500, '65,000', 49500, 72500, '68,000', 66000, 'Rs 39000',
       19000, '₹71,000', '40,500', 56500, '₹16,000', 22000, 29000,
       '₹70,000', '₹37,500', '₹64,500', '57,000', 12500, '₹74,000', 43000,
       '62,500', 49000, '20,500', 'Rs 29000', '₹23,500', '₹22,500',
       '₹59,500', 'Rs 69000', '₹62,000', 41500, '₹19,500', '₹64,000',
       'Rs 62000', 'Rs 32500', 53500, '16,000', '₹52,500', 'Rs 37500',
       '51,500', 61500, 10500, 62000, 54500, 'Rs 31000', '58,500',
       '₹11,000', 68500, '₹10,000', '51,000', 'Rs 26000', 'Rs 47000',
       '26,500', '31,500', 'Rs 41000', '21,500', '20,000', '₹65,500',
       65000, '₹28,000', 'Rs 43500', 67000, 'Rs 65000', '45,500', 48000,
       '₹71,500', 'Rs 60500', '₹49,500', '17,000', '70,500', '56,000',
       '₹33,500', 60500, '₹60,000', '₹36,500', '8,000', '₹39,500',
       'Rs 68500', '₹70,500', '₹26,000', '33,500', '12,500', '34,000',
       61000, 'Rs 20500', '₹32,500', '43,000', 'Rs 10000', 'Rs 63500',
       'Rs 55000', '₹5,500', '₹9,000', '54,500', '55,000', 34500,
       '₹42,000', 'Rs 57000', '₹54,000', 'Rs 69500', '₹20,500', '₹14,500',
       '38,000', '₹35,000', '₹73,500', '₹40,500'], dtype=object)

In [35]:
df["Premium_Amount"]=df["Premium_Amount"].str.replace('₹','')
df["Premium_Amount"]=df["Premium_Amount"].str.replace('Rs ','')
df["Premium_Amount"]=df["Premium_Amount"].str.replace(',','')

In [36]:
df["Premium_Amount"]

0        NaN
1        NaN
2        NaN
3      15500
4        NaN
       ...
993      NaN
994    40500
997      NaN
998      NaN
999      NaN
Name: Premium_Amount, Length: 827, dtype: object

In [37]:
df["Premium_Amount"].isnull().sum()

np.int64(656)

In [38]:
df["Premium_Amount"]=df["Premium_Amount"].astype(float)

In [39]:
df["Premium_Amount"].describe()

count      171.000000
mean     42479.532164
std      21597.614024
min       5000.000000
25%      21250.000000
50%      42000.000000
75%      62750.000000
max      74000.000000
Name: Premium_Amount, dtype: float64

In [40]:
df["Premium_Amount"]=df["Premium_Amount"].fillna(df["Premium_Amount"].mean())

In [41]:
df["Premium_Amount"] = df["Premium_Amount"].astype(int)

In [42]:
df["Premium_Amount"].dtype

dtype('int64')

In [43]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Annual_Income                0
Occupation                   0
Policy_ID                    0
Policy_Type                  0
Premium_Amount               0
Sum_Assured                 91
Policy_Start_Date           49
Years_With_Company           0
Total_Claims                 0
Claim_Amount                67
Late_Payment_Count           0
Previous_Renewals            0
Satisfaction_Score           0
Auto_Renewal_Enabled         0
Agent_ID                     0
Agent_Rating                 0
Renewal_Status_Next_Year     0
dtype: int64

In [44]:
df["Sum_Assured"].dtype

dtype('O')

In [45]:
df["Sum_Assured"].unique()

array(['₹4,650,000', 1400000, '₹4,450,000', nan, 4300000, 1450000,
       'Rs 3500000', 800000, 2300000, 4700000, '₹3,100,000', 3200000,
       '650,000', 3750000, 2950000, 3100000, 4600000, 'Rs 4500000',
       4000000, 1500000, 2100000, 2750000, 2150000, 1050000, 2400000,
       '3,200,000', 1700000, 'Rs 950000', 2450000, 1350000, '4,750,000',
       4750000, 3350000, 3650000, '4,850,000', 1750000, 950000, 700000,
       4250000, 3000000, 4400000, 2550000, 750000, 1650000, '₹350,000',
       '₹2,050,000', 'Rs 750000', 3700000, 550000, 3850000, 1100000,
       4900000, 'Rs 650000', 200000, 'Rs 3050000', 4450000, '₹950,000',
       '₹3,300,000', 3600000, 150000, 3400000, 1950000, '3,150,000',
       1550000, 2700000, 4500000, '₹500,000', 350000, 2500000,
       '2,350,000', 1800000, 3050000, 4350000, '₹3,700,000', 3150000,
       'Rs 3400000', 'Rs 1550000', '2,650,000', 'Rs 500000', 1300000,
       4850000, 4800000, 2050000, 'Rs 1500000', '700,000', '750,000',
       '3,850,000', 4150000, 600000, 1900000, '₹1,400,000', 850000,
       '₹250,000', '1,400,000', '₹2,150,000', 4550000, 'Rs 2050000',
       'Rs 4750000', 3500000, 3300000, 2650000, 'Rs 4200000', '1,050,000',
       '2,100,000', '₹4,550,000', 4950000, '1,450,000', 650000,
       '2,450,000', '₹1,750,000', 1850000, '₹2,850,000', 2000000,
       '₹1,200,000', 2800000, 3800000, '350,000', '3,250,000', 100000,
       3900000, 1150000, 'Rs 2300000', 2250000, '₹400,000', 3550000,
       1250000, 'Rs 4950000', '1,550,000', 400000, 'Rs 2450000',
       '₹1,650,000', '₹2,400,000', 1600000, '₹2,950,000', '4,650,000',
       4100000, 4650000, '2,750,000', '3,700,000', 2200000, '₹1,450,000',
       '₹3,750,000', 500000, '4,050,000', 'Rs 1950000', 'Rs 4600000',
       2850000, 450000, 'Rs 2000000', '₹2,700,000', '₹3,400,000', 3950000,
       '3,300,000', 'Rs 1750000', 2350000, 'Rs 100000', '₹1,350,000',
       1200000, '2,600,000', '₹3,350,000', 'Rs 2200000', '₹4,950,000',
       'Rs 1450000', '₹2,600,000', '₹1,100,000', '₹4,000,000',
       '₹2,500,000', 900000, 'Rs 2600000', '₹3,850,000', 3250000,
       '₹450,000', 2600000, '₹2,000,000', 300000, '1,000,000',
       '3,800,000', '3,600,000', '2,850,000', 'Rs 1400000', 3450000,
       '₹2,250,000', '4,150,000', '₹2,750,000', '₹4,250,000',
       'Rs 4000000', 250000, '₹1,500,000', 'Rs 1700000', 4050000,
       '4,300,000', '3,450,000', 'Rs 2800000', 4200000, 'Rs 3150000',
       '₹4,150,000', '₹150,000', '3,750,000', '1,500,000', '300,000',
       '₹4,700,000', '₹1,950,000', 'Rs 2150000', 'Rs 1900000',
       '4,000,000', 'Rs 1850000', 'Rs 1200000', '₹3,800,000', '3,350,000',
       '₹3,550,000', '3,550,000', 'Rs 2400000', 'Rs 3950000',
       '₹4,500,000', '₹3,200,000', '₹4,100,000', '1,300,000', '₹600,000',
       'Rs 2550000', 'Rs 4400000', '₹1,000,000', '4,600,000',
       '₹1,550,000', '₹1,050,000', '₹700,000', 'Rs 2650000', '1,850,000',
       'Rs 4100000', 1000000, 2900000, '1,350,000', '₹4,900,000',
       '200,000', '2,250,000', 'Rs 900000', '₹1,300,000', '₹1,150,000',
       'Rs 1300000', '800,000', '950,000', '₹2,650,000', '₹800,000',
       '2,700,000', '3,950,000', '1,650,000', 'Rs 3200000', '₹3,450,000',
       'Rs 450000', '₹4,800,000', '4,500,000'], dtype=object)

In [46]:
df["Sum_Assured"]=df["Sum_Assured"].str.replace(",","")
df["Sum_Assured"]=df["Sum_Assured"].str.replace("₹","")
df["Sum_Assured"]=df["Sum_Assured"].str.replace("Rs ","")

In [47]:
df["Sum_Assured"]=df["Sum_Assured"].astype(float)

In [48]:
df["Sum_Assured"].describe()

count    2.010000e+02
mean     2.502239e+06
std      1.381379e+06
min      1.000000e+05
25%      1.350000e+06
50%      2.500000e+06
75%      3.700000e+06
max      4.950000e+06
Name: Sum_Assured, dtype: float64

In [49]:
df["Sum_Assured"]=df["Sum_Assured"].fillna(df["Sum_Assured"].mean())

In [50]:
df["Sum_Assured"]=df["Sum_Assured"].astype(int)

In [51]:
df["Sum_Assured"].dtypes

dtype('int64')

In [52]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Annual_Income                0
Occupation                   0
Policy_ID                    0
Policy_Type                  0
Premium_Amount               0
Sum_Assured                  0
Policy_Start_Date           49
Years_With_Company           0
Total_Claims                 0
Claim_Amount                67
Late_Payment_Count           0
Previous_Renewals            0
Satisfaction_Score           0
Auto_Renewal_Enabled         0
Agent_ID                     0
Agent_Rating                 0
Renewal_Status_Next_Year     0
dtype: int64

In [53]:
df["Policy_Start_Date"].dtype

dtype('O')

In [54]:
df["Policy_Start_Date"].unique()

array([42261, 44917, 42779, nan, '14/07/2021', 43225, '2015_03_18', 41737,
       43242, '15/02/2014', 45061, 42077, '2023_07_23', 43692, 42957,
       42591, '01-Sep-2022', 45252, 43592, 44544, '2016_02_21', 46382,
       44509, 45173, 41927, 44756, 44990, 42610, 44450, 42812,
       '2019_02_19', '2020_03_25', 41832, 43818, 44624, 46032, 44538,
       44454, 44678, '2021_11_03', 42241, 44980, 45413, 45606, 46238,
       42101, '2019_05_05', 42470, 42182, 42583, 42039, '2026_04_16',
       44193, '04/12/2016', 44915, 42749, '12/07/2017', 44327, 42047,
       45815, 42403, 43299, 41769, 43302, '27/09/2016', 42604, 44396,
       44623, 43804, '10-Aug-2023', 43544, 45645, '18-Jun-2014', 44671,
       41888, 41900, 42671, 45510, 41871, 43683, 43658, '13/12/2014',
       41873, 45326, '18/09/2021', '2024_01_05', 43834, 45468,
       '10-Aug-2024', '2023_10_23', 43621, 43378, 44297, 42615,
       '2022_04_17', 45282, '20-May-2020', 45379, '11/05/2017', 46331,
       '04/03/2022', 46006, 42717, 44310, 45876, 43183, 44645,
       '20-Feb-2018', 44311, 41726, 43076, 42618, 42809, 44131,
       '20-Oct-2024', 44930, 42913, '23/03/2015', '2014_01_17', 44984,
       44789, 44611, 43978, 42668, 43972, 41660, '16/03/2026', 45643,
       44879, 45636, 44360, 43353, 45640, 42857, 44000, 44386, 46160,
       41974, 44319, 43164, 44543, '2024_04_07', 43041, 46260,
       '2017_01_24', 46235, '2023_08_23', 46224, 42776, 42565,
       '2015_07_23', 44583, 42461, 42010, 42985, 45284, 45487,
       '2020_08_21', '14/03/2018', 45985, '19/12/2021', 45547, 42190,
       44656, 42179, 42878, '24/12/2023', 45924, 45497, 44903, 45232,
       43367, 42433, 45630, 44647, 42647, 46309, 42288, '21/08/2024',
       44746, 43848, 46055, 43653, '17/07/2018', 44896, '19-Jan-2023',
       45785, 43125, 44755, 43880, '2016_04_17', 45610, 41892, 44214,
       44299, 42840, 42108, 45725, '18-Aug-2025', 43196, '2014_07_07',
       42828, 41898, '2017_08_20', 45367, 45119, 45672, '2025_10_15',
       42628, 45728, 44646, 46156, 45424, 44916, '16-Dec-2018', 42413,
       '26-Apr-2019', 44954, 45099, 41946, 43530, 44736, '2017_10_13',
       45607, 42708, 43983, '2018_02_28', '07/05/2016', 43527, 43574,
       45791, '11/06/2019', '15-Apr-2023', 42640, 44216, 41687,
       '16/02/2024', '2025_12_07', '05/08/2014', 41754, 46204, 45608,
       '23/06/2019', 45151, '2016_08_21', '18/05/2014', '11-May-2014',
       '2014_07_23', 43172, 45170, 46063, 42597, 43024, '01-Feb-2020',
       41977, 45255, 41800, '07/06/2018', '13-Jul-2019', 42881, 42557,
       45342, 44714, 44004, '2016_02_25', 42701, 42731, '2019_03_27',
       42019, 44982, 42452, 42494, 43239, '2022_02_19', '28-Sep-2016',
       45396, 45705, 46271, '05/12/2025', 42518, 45722, 43332, 41753,
       '2022_10_04', 44092, 42795, '2014_04_10', 41711, '20-Jul-2018',
       '2017_05_13', '2020_02_15', '2025_07_16', 41662, '01/05/2015',
       41814, '2019_03_02', 42982, 44691, 45116, '2019_11_07',
       '19/05/2022', '2019_10_26', '07/05/2025', '22/06/2015', 43887,
       44787, 44677, '19-Nov-2021', 42407, 43736, '12/08/2025',
       '02/05/2026', 42106, 41887, '2017_03_24', 42516, 43020,
       '18-Aug-2015', 43857, '2018_12_13', 43067, 42931, 42973,
       '03/03/2021', 41777, '12-Dec-2014', '2019_10_11', 42891, 45343,
       '09/09/2024', '02-Apr-2016', 44106, '14-Aug-2026', 43911,
       '2014_08_13', 45325, 44582, '2021_06_23', 44212, '2023_04_23',
       41860, 43685, 44221, '2020_05_19', '26-Nov-2015', 45540, 44933,
       43550, 46334, 46338, 43006, '2016_09_16', 43017, 44097, 45083,
       '2019_03_24', '2021_03_04', 45585, 45213, 42496, '2018_09_01',
       42589, 44152, 46198, '08-May-2020', '2016_09_18', 44737, 44759,
       '15/11/2026', '19/04/2024', 45491, '17/05/2018', 41915,
       '2023_04_14', 45675, '18/02/2021', 44313, '15-Jul-2024',
       '24-May-2026', '2024_12_03', 43010, 42727, '03-Jul-2024',
       '08/04/2014', 41713, 42274, '09/06/2021', 44502, 45376, 44664,
       41689, 44111, 44384, 45277, 46231, 43352, 43840, '11/10/2025',
       45809, '14-Jan-2018', '2017_01_19', 43348, '07-Mar-2020', 43093,
       43660, 43789, '2019_12_18', 42290, 45484, 42062, '02-Mar-2017',
       42544, 45311, 46067, 42729, 43089, 43591, 42923, 44867, 42022,
       43790, 45914, 42412, 43246, 45313, 45025.0, 43030, 43476, 42656,
       '24-Mar-2026', '10-Jun-2017', 42374, '2024_03_05', 43672, 44022,
       42621, 41751, 46122, 46098, 44968, 41797, 41809, 43227,
       '06-Jan-2020', '14/08/2019', '10/12/2018', '11/02/2017', 45062,
       45128, 41997, '2020_10_17', 45220, 43869, '10-Apr-2024', 43745,
       '2022_09_17', '22/11/2015', '04-Sep-2019', 43674, '11/03/2025',
       44197, 44720, 45010, 45531, 43563, '05/09/2017', 42800, 46101,
       '25-Jul-2015', '13-Oct-2025', 45049, '2021_09_24', 43510,
       '15-Feb-2021', 44738, '2017_09_26', 43623, 45034, 44675, 43358,
       '18-Feb-2021', '04-Aug-2021', 44951, '14-Aug-2019', 45319,
       '28/01/2016', 42835, 46064, '01/02/2014', '2014_11_21', 43106,
       '2020_11_02', 44778, 44940, 44817, 45368, 42932, '07/05/2020',
       43705, '12-May-2019', '2014_07_16', 41944, '18/11/2014', 41688,
       44151, 46011, '27/09/2014', 42011, 46253, 41866, '09/05/2023',
       43755, 41698, '17/06/2017', 45244, 41640, 46297, '16-Sep-2024',
       '2025_06_12', 43507, '2026_11_19', '2025_05_13', '22-Jan-2023',
       '07/07/2025', 46028, '05/06/2025', 44799, 42858, 41964,
       '2022_05_03', 42072, '13/01/2021', 42007, 42481, 46117,
       '18/03/2022', 43230, 45086, 41786, 43416, 45071, 42952, 43914,
       44991, 42358, 43765, '16/10/2014', '25/10/2015', '2015_10_04',
       42430, '2014_05_12', 46058, 44156, 44031, 42938, 44255, 42388,
       '14-Oct-2016', 45968, 44820, 43439, 45846, 43916, '06/10/2021',
       43211, 44186, 41967, 43448, '2016_03_09', '10/10/2015', 42561,
       '25-Jun-2018', 45063, '22/12/2022', '08-May-2019', 42868, 46128,
       42832, 44615, '09/08/2026', '13/08/2014', 43275, 41782, 44364,
       44274, '2019_09_13', 42382, 44071, 45191, 45891, 41783,
       '2026_08_17', 43928, 42963, 42771, 45135, 42160, '16/03/2018',
       44858, 42040, 46292, 45700, 45726, 45032, '07/05/2017', 45012,
       '2019_01_23', '2020_07_14', 46145, '2025_03_11', 45677, 46249,
       43815, '18-Aug-2018', 42512, 42837, 43577, 42417, '2022_02_10',
       45451, 41818, 42568, 44421, '2020_06_24', 43810, 45871, 42860,
       42700, 45243, 42566, 42378, 44870, 46363, '13/03/2018', 43902,
       44432, '2026_03_23', 43702, 41720, 44953, 43141, 42819, 42758,
       '27-Nov-2015', 42567, 43354, 43170, 42914, 45979, 42135,
       '2026_08_26', 44475, 42188, 46089, 45818, 43652, 44608, 42431,
       '2022_05_19', '20/05/2019', 42294, 43647, 43603, 46274,
       '06/09/2024', '2015_12_14', 43536, 45814, 45069, 43889, 43237,
       42871, 42543, 42332, 43133, 46218, '16/07/2015', 45802,
       '06/01/2021', '2019_07_18', '19/10/2023', 42051, 41904,
       '01/04/2017', '19-Jun-2020', 43318, 42177, '05/12/2015', 45831,
       45171, 44378, 43990, '03-Nov-2024', '13/07/2025', 44363,
       '08/12/2022', 44625, 43383, 46009, 42748, 45945, 42663, 42115,
       45847, 42777, 42799, '04/04/2018', 45073, 44013, 43775, 44747,
       44329, 43218, 42762, 45080, 43511, '2021_02_27', 44115, 42363,
       '12/02/2018', 45836, 44798, 46069, 41836, 45697, '04/01/2016',
       '27/02/2015', 42506, '12/11/2014', '2015_03_01', '2025_04_16',
       42781, 45717, 44239, 44909, 45434, '10/12/2016', 43060, 44844,
       '2017_05_27', 43537, '2025_12_01', 43436, 44420, 43984, 42371,
       43909, '11-Jul-2020', '2020_05_12', '19/01/2023', '2018_02_12',
       45981, '14/12/2020', 44382], dtype=object)

In [55]:
import pandas as pd
import numpy as np

def clean_date(x):
    
    if pd.isna(x):
        return np.nan
    
    # Excel serial date
    if isinstance(x, (int, float)):
        return pd.to_datetime(x, unit='D', origin='1899-12-30')
    
    x = str(x)
    
    # YYYY_MM_DD
    if '_' in x:
        return pd.to_datetime(x, format='%Y_%m_%d', errors='coerce')
    
    # DD/MM/YYYY
    if '/' in x:
        return pd.to_datetime(x, dayfirst=True, errors='coerce')
    
    # DD-Mon-YYYY
    return pd.to_datetime(x, errors='coerce')


df['Policy_Start_Date'] = df['Policy_Start_Date'].apply(clean_date)

In [56]:
df['Policy_Start_Date'].unique()

<DatetimeArray>
['2015-09-14 00:00:00', '2022-12-22 00:00:00', '2017-02-13 00:00:00',
                 'NaT', '2021-07-14 00:00:00', '2018-05-05 00:00:00',
 '2015-03-18 00:00:00', '2014-04-08 00:00:00', '2018-05-22 00:00:00',
 '2014-02-15 00:00:00',
 ...
 '2018-12-02 00:00:00', '2021-08-12 00:00:00', '2020-06-02 00:00:00',
 '2016-01-02 00:00:00', '2020-03-19 00:00:00', '2020-07-11 00:00:00',
 '2020-05-12 00:00:00', '2025-11-20 00:00:00', '2020-12-14 00:00:00',
 '2021-07-05 00:00:00']
Length: 725, dtype: datetime64[ns]

In [57]:
df['Policy_Start_Date'].isnull().sum()

np.int64(49)

In [58]:
df[df['Policy_Start_Date'].isna()]

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
3,CUST00004,Neha Yadav,27,Other,Kanpur,uttar pradesh,1480000,Retired,POL41571,Travel,...,7,0.0,0,4,2,5,Yes,AG126,4.3,Not Renewed
5,CUST00001,Sneha Mehta,28,Female,Pune,Maharashtra,1480000,Housewife,POL82845,Term,...,0,0.0,₹0,0,0,9,Yes,AG111,4.6,Renewed
31,CUST00032,Vihaan Gupta,34,OTHER,Indore,Madhya Pradesh,1480000,Housewife,POL83989,Travel,...,7,1.0,10000,0,1,5,No,AG110,4.1,Renewed
49,CUST00050,Aditya Desai,20,Male,Kochi,Kerala,2460000,Government Employee,POL59479,TERM,...,10,5.0,125000,2,3,1,No,AG170,3.6,Not Renewed
54,CUST00055,Vihaan Gupta,33,Female,HYDERABAD,Telangana,1480000,Student,POL39603,Vehicle,...,10,0.0,NaN,0,10,1,No,AG143,3.9,Renewed
71,CUST00072,Krishna Kumar,23,Other,Surat,Gujarat,1480000,Self-employed,POL56627,Term,...,2,0.0,NaN,0,1,2,YES,AG129,2.8,Renewed
95,CUST00096,Rahul Reddy,45,Male,Indore,MADHYA PRADESH,1480000,Salaried,POL19514,Vehicle,...,12,0.0,0,0,6,1,Yes,AG170,3.2,Renewed
97,CUST00098,Priya Gupta,54,Female,Bengaluru,Karnataka,1480000,Government Employee,POL57118,Life,...,7,0.0,Rs 0,0,1,5,Yes,AG110,4.3,Not Renewed
133,CUST00134,Rahul Mishra,63,Other,Pune,Maharashtra,1480000,Freelancer,POL30220,Vehicle,...,0,0.0,0,1,0,2,No,AG178,4.8,Not Renewed
134,CUST00135,Krishna Nair,52,Male,Patna,Bihar,1480000,Self-employed,POL78997,Vehicle,...,9,1.0,15000,1,8,10,No,AG102,3.7,Renewed
139,CUST00140,Aarav Desai,48,Male,Ahmedabad,Gujarat,1480000,Housewife,POL80163,Vehicle,...,0,0.0,NaN,0,0,5,Yes,AG125,3.2,Renewed
157,CUST00158,Nisha Sharma,66,Male,Bengaluru,Karnataka,1480000,Salaried,POL96430,Vehicle,...,6,0.0,NaN,1,3,9,No,AG121,3.8,Renewed
165,CUST00166,Meera Verma,64,Female,Ahmedabad,Gujarat,1480000,Housewife,POL58449,Travel,...,0,0.0,Rs 0,1,0,7,Yes,AG107,3.3,Not Renewed
171,CUST00172,Meera Chauhan,62,Female,Vadodara,gujarat,1480000,Salaried,POL34670,Health,...,3,2.0,100000,2,1,8,Yes,AG157,4.9,Not Renewed
220,CUST00221,Riya Jain,37,Female,Pune,Maharashtra,1480000,Salaried,POL46406,Life,...,3,0.0,0,1,2,6,No,AG153,4.7,Not Renewed
223,CUST00224,Myra Gupta,40,Other,Patna,Bihar,1480000,Self-employed,POL46937,VEHICLE,...,5,0.0,0,0,1,7,No,AG137,3.4,Not Renewed
224,CUST00225,Anaya Gupta,42,Female,Rajkot,Gujarat,1480000,BUSINESS,POL26716,Life,...,7,4.0,220000,0,3,7,No,AG130,3.5,Renewed
251,CUST00252,Vihaan Rajput,64,Female,Surat,Gujarat,2340000,Self-employed,POL59063,Travel,...,5,0.0,0,1,1,4,No,AG121,3.6,Not Renewed
278,CUST00279,Myra Joshi,63,Female,Mumbai,Maharashtra,900000,Government Employee,POL80007,Health,...,9,0.0,0,0,9,7,Yes,AG106,3.0,Renewed
286,CUST00287,Rahul Sharma,46,Female,Kochi,Kerala,1480000,Housewife,POL26260,Health,...,9,0.0,₹0,0,3,8,Yes,AG163,4.4,Renewed
297,CUST00266,Arjun Gupta,62,Other,Kochi,Kerala,1480000,Business,POL32890,Travel,...,1,1.0,60000,3,1,10,no,AG161,2.6,Not Renewed
356,CUST00357,Ayaan Jain,43,Male,Coimbatore,tamil nadu,1480000,Self-employed,POL45865,Travel,...,0,2.0,"₹20,000",0,0,9,Yes,AG150,3.9,Renewed
358,CUST00359,Sneha Singh,22,Other,Udaipur,Rajasthan,1480000,freelancer,POL61023,Term,...,3,1.0,15000,5,1,8,No,AG126,4.7,Renewed
372,CUST00373,Ayaan Yadav,42,OTHER,Delhi,Delhi,1480000,Government Employee,POL48686,Life,...,4,3.0,75000,0,4,7,NO,AG106,4.6,Not Renewed
376,CUST00072,Sneha Nair,30,Male,Jaipur,Rajasthan,880000,Freelancer,POL20059,Health,...,11,1.0,"10,000",2,10,1,No,AG155,3.6,Renewed
432,CUST00433,Arjun Yadav,60,Female,Mysuru,karnataka,1180000,Housewife,POL30601,Vehicle,...,10,1.0,55000,0,6,3,No,AG108,4.1,Not Renewed
433,CUST00434,Aadhya Patel,40,Other,Chennai,Tamil Nadu,1480000,SELF-EMPLOYED,POL61456,Term,...,0,4.0,300000,0,0,6,Yes,AG176,4.4,Not Renewed
452,CUST00453,Aditya Mishra,57,Other,Bengaluru,Karnataka,1480000,Government Employee,POL42507,Vehicle,...,11,0.0,0,3,9,2,Yes,AG132,4.6,Renewed
515,CUST00516,Sneha Mishra,62,Male,pune,Maharashtra,1480000,Housewife,POL86611,Life,...,5,2.0,60000,0,2,1,No,AG152,2.9,Renewed
523,CUST00524,Nisha Reddy,61,Female,Surat,Gujarat,590000,Salaried,POL86050,Travel,...,1,1.0,20000,1,1,6,Yes,AG159,4.3,Not Renewed
536,CUST00537,Kavya Patel,50,Female,Surat,gujarat,1480000,Self-employed,POL90626,Health,...,1,2.0,"130,000",0,0,6,Yes,AG152,3.1,Renewed
559,CUST00560,Vihaan Chauhan,55,Other,Kanpur,Uttar Pradesh,1480000,Housewife,POL76721,Term,...,0,0.0,0,4,0,3,Yes,AG149,4.6,Renewed
577,CUST00578,Vihaan Mehta,18,Other,Chennai,Tamil Nadu,2190000,Housewife,POL23448,health,...,8,0.0,Rs 0,2,7,0,Yes,AG115,2.8,Not Renewed
612,CUST00613,Vivaan Gupta,53,Male,Mumbai,Maharashtra,1480000,Government Employee,POL89479,TRAVEL,...,9,1.0,"₹15,000",1,3,5,No,AG111,4.7,Not Renewed
615,CUST00616,Meera Gupta,46,Female,Nashik,MAHARASHTRA,1480000,Retired,POL10382,Health,...,12,2.0,30000,3,10,7,No,AG102,3.1,Not Renewed
636,CUST00637,Rohit Rajput,49,Male,Kolkata,West Bengal,1260000,Business,POL18793,VEHICLE,...,1,0.0,0,0,0,4,No,AG165,3.3,Not Renewed
652,CUST00653,Diya Joshi,31,Male,Udaipur,Rajasthan,1480000,Salaried,POL98362,Travel,...,11,1.0,"₹20,000",1,6,1,No,AG116,4.4,Renewed
709,CUST00710,Aadhya Yadav,30,Female,Kanpur,Uttar Pradesh,1480000,Student,POL27943,Term,...,11,1.0,"₹5,000",1,11,4,Yes,AG155,4.7,Renewed
784,CUST00785,Aadhya Nair,26,Female,Kolkata,West Bengal,1680000,Student,POL13915,Life,...,4,0.0,0,2,1,8,No,AG109,4.9,Not Renewed
797,CUST00719,Aditya Patel,61,OTHER,Hyderabad,Telangana,1480000,Self-employed,POL37771,Term,...,8,0.0,0,0,4,6,No,AG148,3.7,Not Renewed
803,CUST00804,Diya Patel,55,MALE,Delhi,Delhi,1480000,Government Employee,POL58910,Term,...,9,1.0,"₹65,000",3,7,1,no,AG174,4.4,Not Renewed
822,CUST00823,Meera Jain,40,Male,Rajkot,Gujarat,1480000,HOUSEWIFE,POL42208,Vehicle,...,3,3.0,"₹240,000",0,2,4,Yes,AG110,4.6,Not Renewed
839,CUST00840,Aditya Desai,41,Other,Jaipur,Rajasthan,1480000,Business,POL49201,Vehicle,...,1,0.0,₹0,3,0,10,Yes,AG156,4.5,Renewed
843,CUST00844,Sai Gupta,20,Female,Nashik,Maharashtra,1480000,Salaried,POL47742,Life,...,5,0.0,0,0,5,8,NO,AG136,4.7,Not Renewed
845,CUST00846,Myra Nair,45,Male,Lucknow,Uttar Pradesh,1480000,Business,POL16685,Life,...,10,2.0,80000,1,6,3,No,AG137,4.5,Renewed
848,CUST00849,Krishna Nair,58,Female,Mysuru,Karnataka,1480000,Government Employee,POL79253,Vehicle,...,4,0.0,0,0,1,6,No,AG164,3.5,Not Renewed
858,CUST00859,Karan Desai,50,female,Ahmedabad,Gujarat,1480000,Housewife,POL96491,Vehicle,...,3,3.0,90000,0,3,10,Yes,AG173,2.6,Renewed
885,CUST00879,Ayaan Yadav,53,Male,Lucknow,Uttar Pradesh,1480000,Government Employee,POL68048,Life,...,7,0.0,Rs 0,3,5,7,Yes,AG101,3.4,Renewed
988,CUST00989,Saanvi Mehta,30,Female,Surat,Gujarat,1480000,Business,POL15890,Vehicle,...,11,0.0,NaN,1,8,1,Yes,AG152,4.5,Renewed

In [59]:
df = df.dropna(subset=['Policy_Start_Date'])

In [60]:
df.isnull().sum()

Customer_ID                  0
Customer_Name                0
Age                          0
Gender                       0
City                         0
State                        0
Annual_Income                0
Occupation                   0
Policy_ID                    0
Policy_Type                  0
Premium_Amount               0
Sum_Assured                  0
Policy_Start_Date            0
Years_With_Company           0
Total_Claims                 0
Claim_Amount                62
Late_Payment_Count           0
Previous_Renewals            0
Satisfaction_Score           0
Auto_Renewal_Enabled         0
Agent_ID                     0
Agent_Rating                 0
Renewal_Status_Next_Year     0
dtype: int64

In [61]:
df["Claim_Amount"].dtype

dtype('O')

In [62]:
df["Claim_Amount"].unique()

array([nan, 30000, 0, 120000, '₹0', '0', 20000, 45000, 100000, 150000,
       'Rs 0', '150,000', '40,000', 55000, 165000, '45,000', 'Rs 120000',
       '260,000', 135000, 50000, 90000, 180000, 70000, 5000, 75000,
       '₹225,000', 240000, '₹15,000', 15000, 260000, 210000, 140000,
       '₹80,000', '₹10,000', 60000, 110000, 80000, 25000, '₹180,000',
       '₹70,000', 85000, '₹20,000', 160000, '₹55,000', 40000, 275000,
       195000, 10000, 'Rs 40000', 'Rs 50000', 220000, 255000, 'Rs 45000',
       '10,000', 125000, 340000, '₹35,000', '100,000', 200000, 'Rs 70000',
       '85,000', 65000, 'Rs 130000', 'Rs 255000', 170000, '₹45,000',
       '₹25,000', 350000, '280,000', 'Rs 195000', '₹75,000', 'Rs 30000',
       '₹170,000', 105000, '50,000', '₹220,000', '75,000', '35,000',
       '30,000', '175,000', '₹210,000', '₹130,000', 320000, 300000,
       '160,000', '220,000', '25,000', 35000, '₹120,000', 'Rs 180000',
       '130,000', '₹100,000', '₹195,000', '₹90,000', '70,000',
       'Rs 220000', 'Rs 20000', 'Rs 100000', 225000, '₹40,000', '20,000',
       'Rs 300000', 'Rs 65000', '₹60,000', '110,000', '₹320,000'],
      dtype=object)

In [63]:
df["Claim_Amount"]=df["Claim_Amount"].str.replace(",","")
df["Claim_Amount"]=df["Claim_Amount"].str.replace("₹","")
df["Claim_Amount"]=df["Claim_Amount"].str.replace("Rs ","")

In [64]:
import warnings
warnings.filterwarnings('ignore')

In [65]:
df["Claim_Amount"]=df["Claim_Amount"].astype(float)

In [66]:
df["Claim_Amount"].describe()

count       168.000000
mean      45446.428571
std       71859.040237
min           0.000000
25%           0.000000
50%           0.000000
75%       66250.000000
max      320000.000000
Name: Claim_Amount, dtype: float64

In [67]:
df["Claim_Amount"]=df["Claim_Amount"].fillna(df["Claim_Amount"].median())

In [68]:
df["Claim_Amount"]=df["Claim_Amount"].astype(int)

In [69]:
df.dtypes

Customer_ID                         object
Customer_Name                       object
Age                                  int64
Gender                              object
City                                object
State                               object
Annual_Income                        int64
Occupation                          object
Policy_ID                           object
Policy_Type                         object
Premium_Amount                       int64
Sum_Assured                          int64
Policy_Start_Date           datetime64[ns]
Years_With_Company                   int64
Total_Claims                       float64
Claim_Amount                         int64
Late_Payment_Count                   int64
Previous_Renewals                    int64
Satisfaction_Score                  object
Auto_Renewal_Enabled                object
Agent_ID                            object
Agent_Rating                       float64
Renewal_Status_Next_Year            object
dtype: object

In [70]:
df.isnull().sum()

Customer_ID                 0
Customer_Name               0
Age                         0
Gender                      0
City                        0
State                       0
Annual_Income               0
Occupation                  0
Policy_ID                   0
Policy_Type                 0
Premium_Amount              0
Sum_Assured                 0
Policy_Start_Date           0
Years_With_Company          0
Total_Claims                0
Claim_Amount                0
Late_Payment_Count          0
Previous_Renewals           0
Satisfaction_Score          0
Auto_Renewal_Enabled        0
Agent_ID                    0
Agent_Rating                0
Renewal_Status_Next_Year    0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df.dtypes

Customer_ID                         object
Customer_Name                       object
Age                                  int64
Gender                              object
City                                object
State                               object
Annual_Income                        int64
Occupation                          object
Policy_ID                           object
Policy_Type                         object
Premium_Amount                       int64
Sum_Assured                          int64
Policy_Start_Date           datetime64[ns]
Years_With_Company                   int64
Total_Claims                       float64
Claim_Amount                         int64
Late_Payment_Count                   int64
Previous_Renewals                    int64
Satisfaction_Score                  object
Auto_Renewal_Enabled                object
Agent_ID                            object
Agent_Rating                       float64
Renewal_Status_Next_Year            object
dtype: object

In [73]:
df

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,UDAIPUR,Rajasthan,1480000,Self-employed,POL76237,travel,...,10,0.0,0,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,1480000,Self-employed,POL69429,Vehicle,...,10,1.0,0,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,Uttar Pradesh,530000,HOUSEWIFE,POL16175,Health,...,6,0.0,0,1,4,1,No,AG144,2.8,Not Renewed
4,CUST00001,Ayaan Singh,20,Male,Kolkata,West Bengal,1480000,Housewife,POL71993,Term,...,6,0.0,0,1,5,2,Yes,AG125,3.8,Renewed
6,CUST00007,Anaya Jain,31,Female,Bhopal,Madhya Pradesh,2100000,self-employed,POL91416,Travel,...,3,3.0,0,0,1,8,Yes,AG171,3.2,Not Renewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,Government Employee,POL86534,Vehicle,...,9,3.0,0,3,9,1,No,AG106,3.6,Not Renewed
994,CUST00995,Ayaan Nair,42,Female,Chennai,Tamil Nadu,1480000,Retired,POL51303,Travel,...,6,0.0,0,0,0,5,Yes,AG180,3.9,Renewed
997,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1.0,0,0,0,1,No,AG101,4.0,Not Renewed
998,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,GOVERNMENT EMPLOYEE,POL23101,LIFE,...,0,2.0,0,0,0,5,No,AG102,4.6,Not Renewed
999,CUST01000,Kavya Sharma,36,Female,INDORE,Madhya Pradesh,1480000,Student,POL47185,Life,...,10,0.0,0,0,4,4,Yes,AG105,3.4,Renewed

In [74]:
df["Total_Claims"]=df["Total_Claims"].astype(int)

In [75]:
df["Satisfaction_Score"].unique()

array([3, 1, 2, 8, 5, 4, 9, 6, 10, 7, 0, 'good', 11], dtype=object)

In [76]:
df = df[df["Satisfaction_Score"] != "good"]

In [77]:
df["Satisfaction_Score"]=df["Satisfaction_Score"].astype(int)

In [78]:
df

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,UDAIPUR,Rajasthan,1480000,Self-employed,POL76237,travel,...,10,0,0,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,1480000,Self-employed,POL69429,Vehicle,...,10,1,0,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,Uttar Pradesh,530000,HOUSEWIFE,POL16175,Health,...,6,0,0,1,4,1,No,AG144,2.8,Not Renewed
4,CUST00001,Ayaan Singh,20,Male,Kolkata,West Bengal,1480000,Housewife,POL71993,Term,...,6,0,0,1,5,2,Yes,AG125,3.8,Renewed
6,CUST00007,Anaya Jain,31,Female,Bhopal,Madhya Pradesh,2100000,self-employed,POL91416,Travel,...,3,3,0,0,1,8,Yes,AG171,3.2,Not Renewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,Government Employee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
994,CUST00995,Ayaan Nair,42,Female,Chennai,Tamil Nadu,1480000,Retired,POL51303,Travel,...,6,0,0,0,0,5,Yes,AG180,3.9,Renewed
997,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1,0,0,0,1,No,AG101,4.0,Not Renewed
998,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,GOVERNMENT EMPLOYEE,POL23101,LIFE,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed
999,CUST01000,Kavya Sharma,36,Female,INDORE,Madhya Pradesh,1480000,Student,POL47185,Life,...,10,0,0,0,4,4,Yes,AG105,3.4,Renewed

In [79]:
df["Customer_Name"] = df["Customer_Name"].str.title()
df["Gender"] = df["Gender"].str.title()
df["State"] = df["State"].str.title()
df["Occupation"] = df["Occupation"].str.title()
df["Policy_Type"] = df["Policy_Type"].str.title() 
df["Renewal_Status_Next_Year"] = df["Renewal_Status_Next_Year"].str.title()
df["City"] = df["City"].str.title()

In [80]:
df

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,Udaipur,Rajasthan,1480000,Self-Employed,POL76237,Travel,...,10,0,0,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,New Delhi,Delhi,1480000,Self-Employed,POL69429,Vehicle,...,10,1,0,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,Uttar Pradesh,530000,Housewife,POL16175,Health,...,6,0,0,1,4,1,No,AG144,2.8,Not Renewed
4,CUST00001,Ayaan Singh,20,Male,Kolkata,West Bengal,1480000,Housewife,POL71993,Term,...,6,0,0,1,5,2,Yes,AG125,3.8,Renewed
6,CUST00007,Anaya Jain,31,Female,Bhopal,Madhya Pradesh,2100000,Self-Employed,POL91416,Travel,...,3,3,0,0,1,8,Yes,AG171,3.2,Not Renewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,Government Employee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
994,CUST00995,Ayaan Nair,42,Female,Chennai,Tamil Nadu,1480000,Retired,POL51303,Travel,...,6,0,0,0,0,5,Yes,AG180,3.9,Renewed
997,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1,0,0,0,1,No,AG101,4.0,Not Renewed
998,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,Government Employee,POL23101,Life,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed
999,CUST01000,Kavya Sharma,36,Female,Indore,Madhya Pradesh,1480000,Student,POL47185,Life,...,10,0,0,0,4,4,Yes,AG105,3.4,Renewed

In [81]:
df["Gender"].unique()

array(['Other', 'Male', 'Female', ' Male ', ' Other ', ' Female '],
      dtype=object)

In [82]:
df["Gender"]=df["Gender"].str.replace(" ","")

In [83]:
df["Gender"].value_counts()

Gender
Male      265
Other     256
Female    254
Name: count, dtype: int64

In [84]:
df.shape

(775, 23)

In [85]:
df["City"].unique()

array(['Udaipur', 'New Delhi', 'Lucknow', 'Kolkata', 'Bhopal', 'Delhi',
       'Kochi', 'Vadodara', 'Mysuru', 'Nagpur', 'Ahmedabad', 'Kanpur',
       'Indore', 'Coimbatore', 'Chennai', 'Surat', 'Bengaluru', 'Jaipur',
       'Hyderabad', 'Mumbai', 'Nashik', 'Patna', ' Patna ', ' Lucknow ',
       ' New Delhi ', 'Pune', 'Rajkot', ' Ahmedabad ', ' Bengaluru ',
       ' Vadodara ', ' Udaipur ', ' Kolkata ', ' Indore ', ' Coimbatore ',
       ' Bhopal ', ' Nashik ', ' Surat ', ' Hyderabad ', ' Nagpur ',
       ' Mysuru ', ' Kanpur ', ' Kochi '], dtype=object)

In [86]:
df["City"].value_counts()

City
Coimbatore      45
Udaipur         39
Indore          38
Nashik          37
Pune            36
Hyderabad       36
Mumbai          35
Vadodara        34
Bengaluru       32
Kochi           31
Delhi           31
New Delhi       30
Nagpur          30
Mysuru          29
Bhopal          29
Lucknow         28
Chennai         27
Jaipur          26
Rajkot          24
Patna           24
Surat           23
Kanpur          23
Ahmedabad       22
Kolkata         21
 Ahmedabad       5
 Bengaluru       5
 Patna           4
 Lucknow         4
 Vadodara        4
 Surat           4
 New Delhi       3
 Bhopal          2
 Nagpur          2
 Nashik          2
 Kolkata         2
 Coimbatore      2
 Indore          1
 Hyderabad       1
 Udaipur         1
 Mysuru          1
 Kanpur          1
 Kochi           1
Name: count, dtype: int64

In [87]:
df["City"]=df["City"].str.replace(" ","")

In [88]:
df.tail()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
993,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,Government Employee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
994,CUST00995,Ayaan Nair,42,Female,Chennai,Tamil Nadu,1480000,Retired,POL51303,Travel,...,6,0,0,0,0,5,Yes,AG180,3.9,Renewed
997,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1,0,0,0,1,No,AG101,4.0,Not Renewed
998,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,Government Employee,POL23101,Life,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed
999,CUST01000,Kavya Sharma,36,Female,Indore,Madhya Pradesh,1480000,Student,POL47185,Life,...,10,0,0,0,4,4,Yes,AG105,3.4,Renewed

In [89]:
df["State"].unique()

array(['Rajasthan', 'Delhi', 'Uttar Pradesh', ' West Bengal ',
       'Madhya Pradesh', 'Kerala', 'Gujarat', 'Karnataka', 'Maharashtra',
       ' Gujarat ', 'Tamil Nadu', 'Telangana', 'Bihar',
       ' Madhya Pradesh ', 'West Bengal', ' Uttar Pradesh ',
       ' Rajasthan ', ' Tamil Nadu ', ' Delhi ', ' Maharashtra ',
       ' Telangana ', ' Karnataka ', ' Kerala '], dtype=object)

In [90]:
df["State"].value_counts()

State
Maharashtra         131
Gujarat             110
Tamil Nadu           71
Madhya Pradesh       67
Karnataka            64
Rajasthan            62
Delhi                62
Uttar Pradesh        53
Telangana            35
Kerala               30
Bihar                28
West Bengal          22
 Maharashtra         11
 Gujarat              6
 Rajasthan            4
 Madhya Pradesh       3
 Uttar Pradesh        3
 Tamil Nadu           3
 Karnataka            3
 Delhi                2
 Telangana            2
 Kerala               2
 West Bengal          1
Name: count, dtype: int64

In [91]:
df["State"]=df["State"].str.replace(" ", "")

In [92]:
df["Occupation"].unique()

array(['Self-Employed', 'Housewife', 'Retired', 'Freelancer', 'Student',
       'Salaried', 'Business', 'Government Employee', ' Freelancer ',
       ' Business ', ' Housewife ', ' Salaried ', ' Self-Employed ',
       ' Retired ', ' Student ', ' Government Employee '], dtype=object)

In [93]:
df["Occupation"].value_counts()

Occupation
Government Employee      104
Retired                   94
Salaried                  93
Self-Employed             92
Student                   91
Business                  88
Housewife                 86
Freelancer                79
 Salaried                  9
 Housewife                 8
 Retired                   6
 Student                   6
 Business                  5
 Self-Employed             5
 Government Employee       5
 Freelancer                4
Name: count, dtype: int64

In [94]:
df["Occupation"]=df["Occupation"].str.replace(" ","")

In [95]:
df.tail()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
993,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,GovernmentEmployee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
994,CUST00995,Ayaan Nair,42,Female,Chennai,TamilNadu,1480000,Retired,POL51303,Travel,...,6,0,0,0,0,5,Yes,AG180,3.9,Renewed
997,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1,0,0,0,1,No,AG101,4.0,Not Renewed
998,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,GovernmentEmployee,POL23101,Life,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed
999,CUST01000,Kavya Sharma,36,Female,Indore,MadhyaPradesh,1480000,Student,POL47185,Life,...,10,0,0,0,4,4,Yes,AG105,3.4,Renewed

In [96]:
df = df.reset_index(drop=True)

In [97]:
df[df["Occupation"]=="GovernmentEmployee"]

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
16,CUST00022,Arjun Singh,48,Other,Indore,MadhyaPradesh,1480000,GovernmentEmployee,POL92155,Term,...,1,3,0,0,0,2,yes,AG108,3.2,Renewed
23,CUST00031,Saanvi Chauhan,22,Female,Vadodara,Gujarat,1480000,GovernmentEmployee,POL64747,Vehicle,...,2,2,0,0,0,4,Yes,AG140,4.4,Not Renewed
26,CUST00035,Saanvi Mehta,37,Male,Lucknow,UttarPradesh,1480000,GovernmentEmployee,POL64874,Life,...,0,0,0,2,0,5,No,AG119,4.6,Not Renewed
29,CUST00039,Sai Sharma,27,Female,Vadodara,Gujarat,1480000,GovernmentEmployee,POL14244,Travel,...,5,0,0,0,2,4,Yes,AG150,4.8,Not Renewed
38,CUST00051,Aarav Mehta,31,Female,Patna,Bihar,1480000,GovernmentEmployee,POL80747,Life,...,8,3,0,0,2,9,Yes,AG176,4.7,Renewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,CUST00932,Meera Nair,49,Female,Chennai,TamilNadu,1540000,GovernmentEmployee,POL60344,Vehicle,...,3,0,0,1,1,4,Yes,AG156,4.8,Renewed
726,CUST00933,Anaya Rajput,0,Female,Chennai,TamilNadu,1820000,GovernmentEmployee,POL19966,Vehicle,...,3,1,0,1,0,8,Yes,AG147,3.0,Renewed
763,CUST00984,Sai Jain,18,Male,Bengaluru,Karnataka,1480000,GovernmentEmployee,POL95239,Vehicle,...,5,2,0,0,4,1,No,AG111,4.7,Not Renewed
770,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,GovernmentEmployee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
773,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,GovernmentEmployee,POL23101,Life,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed

In [98]:
df["Occupation"] = df["Occupation"].replace(
    "GovernmentEmployee",
    "Government Employee"
)

In [99]:
df["Policy_ID"].value_counts()

Policy_ID
POL42576    2
POL76237    1
POL95607    1
POL28555    1
POL89023    1
           ..
POL16683    1
POL90779    1
POL89502    1
POL59996    1
POL47185    1
Name: count, Length: 774, dtype: int64

In [100]:
df["Policy_Type"].unique()

array(['Travel', 'Vehicle', 'Health', 'Term', 'Life', ' Term ',
       ' Travel ', ' Vehicle ', ' Life ', ' Health '], dtype=object)

In [101]:
df["Policy_Type"]=df["Policy_Type"].str.replace(" ","")

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               775 non-null    object
 1   Customer_Name             775 non-null    object
 2   Age                       775 non-null    int64
 3   Gender                    775 non-null    object
 4   City                      775 non-null    object
 5   State                     775 non-null    object
 6   Annual_Income             775 non-null    int64
 7   Occupation                775 non-null    object
 8   Policy_ID                 775 non-null    object
 9   Policy_Type               775 non-null    object
 10  Premium_Amount            775 non-null    int64
 11  Sum_Assured               775 non-null    int64
 12  Policy_Start_Date         775 non-null    datetime64[ns]
 13  Years_With_Company        775 non-null    int64
 14  Total_Claims              775 non-null    int64
 15  Claim_Amount              775 non-null    int64
 16  Late_Payment_Count        775 non-null    int64
 17  Previous_Renewals         775 non-null    int64
 18  Satisfaction_Score        775 non-null    int64
 19  Auto_Renewal_Enabled      775 non-null    object
 20  Agent_ID                  775 non-null    object
 21  Agent_Rating              775 non-null    float64
 22  Renewal_Status_Next_Year  775 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(10), object(11)
memory usage: 139.4+ KB

In [103]:
df["Auto_Renewal_Enabled"].unique()

array(['Yes', 'No', 'yes', 'no', ' No ', 'YES', ' Yes ', 'NO'],
      dtype=object)

In [104]:
df["Auto_Renewal_Enabled"]=df["Auto_Renewal_Enabled"].str.replace(" ","")
df["Auto_Renewal_Enabled"]=df["Auto_Renewal_Enabled"].str.replace('yes','Yes')
df["Auto_Renewal_Enabled"]=df["Auto_Renewal_Enabled"].str.replace('YES','Yes')
df["Auto_Renewal_Enabled"]=df["Auto_Renewal_Enabled"].str.replace('NO','No')
df["Auto_Renewal_Enabled"]=df["Auto_Renewal_Enabled"].str.replace('no','No')

In [105]:
df.tail()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
770,CUST00994,Diya Singh,39,Male,Mumbai,Maharashtra,550000,Government Employee,POL86534,Vehicle,...,9,3,0,3,9,1,No,AG106,3.6,Not Renewed
771,CUST00995,Ayaan Nair,42,Female,Chennai,TamilNadu,1480000,Retired,POL51303,Travel,...,6,0,0,0,0,5,Yes,AG180,3.9,Renewed
772,CUST00998,Sai Desai,55,Male,Udaipur,Rajasthan,1480000,Salaried,POL19840,Term,...,4,1,0,0,0,1,No,AG101,4.0,Not Renewed
773,CUST00999,Ayaan Yadav,34,Other,Patna,Bihar,1480000,Government Employee,POL23101,Life,...,0,2,0,0,0,5,No,AG102,4.6,Not Renewed
774,CUST01000,Kavya Sharma,36,Female,Indore,MadhyaPradesh,1480000,Student,POL47185,Life,...,10,0,0,0,4,4,Yes,AG105,3.4,Renewed

In [106]:
df["Agent_ID"].value_counts()

Agent_ID
AG179    20
AG120    19
AG108    18
AG153    16
AG174    16
         ..
AG141     5
AG159     5
AG172     3
AG137     3
AG177     2
Name: count, Length: 80, dtype: int64

In [107]:
df["Renewal_Status_Next_Year"].unique()

array(['Not Renewed', 'Renewed', ' Not Renewed '], dtype=object)

In [108]:
df["Renewal_Status_Next_Year"].value_counts()

Renewal_Status_Next_Year
Renewed          430
Not Renewed      343
 Not Renewed       2
Name: count, dtype: int64

In [109]:
df["Renewal_Status_Next_Year"]=df["Renewal_Status_Next_Year"].str.replace(" ","")

In [110]:
df["Renewal_Status_Next_Year"].value_counts()

Renewal_Status_Next_Year
Renewed       430
NotRenewed    345
Name: count, dtype: int64

In [111]:
df["Renewal_Status_Next_Year"]=df["Renewal_Status_Next_Year"].str.replace("NotRenewed","Not Renewed")

In [112]:
df["Renewal_Status_Next_Year"].value_counts()

Renewal_Status_Next_Year
Renewed        430
Not Renewed    345
Name: count, dtype: int64

In [113]:
df.head()

,Customer_ID,Customer_Name,Age,Gender,City,State,Annual_Income,Occupation,Policy_ID,Policy_Type,...,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_ID,Agent_Rating,Renewal_Status_Next_Year
0,CUST00001,Aarav Jain,33,Other,Udaipur,Rajasthan,1480000,Self-Employed,POL76237,Travel,...,10,0,0,2,0,3,Yes,AG144,2.8,Not Renewed
1,CUST00002,Nisha Chauhan,54,Other,NewDelhi,Delhi,1480000,Self-Employed,POL69429,Vehicle,...,10,1,0,1,3,3,Yes,AG108,3.1,Renewed
2,CUST00003,Krishna Gupta,33,Other,Lucknow,UttarPradesh,530000,Housewife,POL16175,Health,...,6,0,0,1,4,1,No,AG144,2.8,Not Renewed
3,CUST00001,Ayaan Singh,20,Male,Kolkata,WestBengal,1480000,Housewife,POL71993,Term,...,6,0,0,1,5,2,Yes,AG125,3.8,Renewed
4,CUST00007,Anaya Jain,31,Female,Bhopal,MadhyaPradesh,2100000,Self-Employed,POL91416,Travel,...,3,3,0,0,1,8,Yes,AG171,3.2,Not Renewed

In [114]:
df.to_csv("clean.csv")

In [115]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State',
       'Annual_Income', 'Occupation', 'Policy_ID', 'Policy_Type',
       'Premium_Amount', 'Sum_Assured', 'Policy_Start_Date',
       'Years_With_Company', 'Total_Claims', 'Claim_Amount',
       'Late_Payment_Count', 'Previous_Renewals', 'Satisfaction_Score',
       'Auto_Renewal_Enabled', 'Agent_ID', 'Agent_Rating',
       'Renewal_Status_Next_Year'],
      dtype='object')

In [116]:
df["Policy_Year"]=df["Policy_Start_Date"].dt.year
df["Policy_Month"]=df["Policy_Start_Date"].dt.month

In [117]:
x=df.drop(["Customer_ID","Policy_ID","Agent_ID","Policy_Start_Date","Renewal_Status_Next_Year","Customer_Name"],axis=1)

In [118]:
x

,Age,Gender,City,State,Annual_Income,Occupation,Policy_Type,Premium_Amount,Sum_Assured,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Auto_Renewal_Enabled,Agent_Rating,Policy_Year,Policy_Month
0,33,Other,Udaipur,Rajasthan,1480000,Self-Employed,Travel,42479,4650000,10,0,0,2,0,3,Yes,2.8,2015,9
1,54,Other,NewDelhi,Delhi,1480000,Self-Employed,Vehicle,42479,2502238,10,1,0,1,3,3,Yes,3.1,2022,12
2,33,Other,Lucknow,UttarPradesh,530000,Housewife,Health,42479,4450000,6,0,0,1,4,1,No,2.8,2017,2
3,20,Male,Kolkata,WestBengal,1480000,Housewife,Term,42479,2502238,6,0,0,1,5,2,Yes,3.8,2021,7
4,31,Female,Bhopal,MadhyaPradesh,2100000,Self-Employed,Travel,42479,3500000,3,3,0,0,1,8,Yes,3.2,2018,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,39,Male,Mumbai,Maharashtra,550000,Government Employee,Vehicle,42479,2502238,9,3,0,3,9,1,No,3.6,2023,1
771,42,Female,Chennai,TamilNadu,1480000,Retired,Travel,40500,2502238,6,0,0,0,0,5,Yes,3.9,2018,2
772,55,Male,Udaipur,Rajasthan,1480000,Salaried,Term,42479,2502238,4,1,0,0,0,1,No,4.0,2025,11
773,34,Other,Patna,Bihar,1480000,Government Employee,Life,42479,4500000,0,2,0,0,0,5,No,4.6,2020,12
774,36,Female,Indore,MadhyaPradesh,1480000,Student,Life,42479,2502238,10,0,0,0,4,4,Yes,3.4,2021,7

In [119]:
y=df["Renewal_Status_Next_Year"]

In [120]:
y

0      Not Renewed
1          Renewed
2      Not Renewed
3          Renewed
4      Not Renewed
          ...
770    Not Renewed
771        Renewed
772    Not Renewed
773    Not Renewed
774        Renewed
Name: Renewal_Status_Next_Year, Length: 775, dtype: object

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size=0.8,random_state=42)

In [123]:
y_train

133    Not Renewed
753    Not Renewed
55         Renewed
405        Renewed
673        Renewed
          ...
71         Renewed
106    Not Renewed
270        Renewed
435        Renewed
102        Renewed
Name: Renewal_Status_Next_Year, Length: 620, dtype: object

In [124]:
print(x_train.shape)

(620, 19)

In [125]:
print(x_test.shape)

(155, 19)

In [126]:
print(y_train.shape)

(620,)

In [127]:
x.dtypes

Age                       int64
Gender                   object
City                     object
State                    object
Annual_Income             int64
Occupation               object
Policy_Type              object
Premium_Amount            int64
Sum_Assured               int64
Years_With_Company        int64
Total_Claims              int64
Claim_Amount              int64
Late_Payment_Count        int64
Previous_Renewals         int64
Satisfaction_Score        int64
Auto_Renewal_Enabled     object
Agent_Rating            float64
Policy_Year               int32
Policy_Month              int32
dtype: object

In [128]:
print(y_test.shape)

(155,)

In [129]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [130]:
ohe= OneHotEncoder(drop='first')

In [131]:
x_train_new=ohe.fit_transform(x_train[["Gender","City","State","Occupation","Policy_Type","Auto_Renewal_Enabled"]]).toarray()
x_test_new=ohe.transform(x_test[["Gender","City","State","Occupation","Policy_Type","Auto_Renewal_Enabled"]]).toarray()

In [132]:
x_train_new

array([[0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 1.]], shape=(620, 48))

In [133]:
x.dtypes

Age                       int64
Gender                   object
City                     object
State                    object
Annual_Income             int64
Occupation               object
Policy_Type              object
Premium_Amount            int64
Sum_Assured               int64
Years_With_Company        int64
Total_Claims              int64
Claim_Amount              int64
Late_Payment_Count        int64
Previous_Renewals         int64
Satisfaction_Score        int64
Auto_Renewal_Enabled     object
Agent_Rating            float64
Policy_Year               int32
Policy_Month              int32
dtype: object

In [134]:
x_train_encode=np.hstack((x_train[['Age', 'Annual_Income', 'Sum_Assured', 'Years_With_Company','Total_Claims','Claim_Amount','Late_Payment_Count','Previous_Renewals','Satisfaction_Score','Agent_Rating','Policy_Year','Policy_Month']].values,x_train_new))

In [135]:
x_test_encode=np.hstack((x_test[['Age', 'Annual_Income', 'Sum_Assured', 'Years_With_Company','Total_Claims','Claim_Amount','Late_Payment_Count','Previous_Renewals','Satisfaction_Score','Agent_Rating','Policy_Year','Policy_Month']].values,x_test_new))

In [136]:
x_train_encode

array([[6.200000e+01, 1.480000e+06, 2.502238e+06, ..., 1.000000e+00,
        0.000000e+00, 0.000000e+00],
       [4.200000e+01, 1.500000e+06, 2.502238e+06, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [6.300000e+01, 1.350000e+06, 2.502238e+06, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       ...,
       [6.300000e+01, 1.480000e+06, 4.600000e+06, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00],
       [5.500000e+01, 1.480000e+06, 2.502238e+06, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [5.000000e+01, 1.480000e+06, 2.502238e+06, ..., 1.000000e+00,
        0.000000e+00, 1.000000e+00]], shape=(620, 60))

In [137]:
num_cols = [
    'Age', 'Annual_Income', 'Sum_Assured', 'Years_With_Company',
    'Total_Claims', 'Claim_Amount', 'Late_Payment_Count',
    'Previous_Renewals', 'Satisfaction_Score', 'Agent_Rating',
    'Policy_Year', 'Policy_Month'
]

cat_cols = list(ohe.get_feature_names_out([
    'Gender', 'City', 'State', 'Occupation',
    'Policy_Type', 'Auto_Renewal_Enabled'
]))

all_cols = num_cols + cat_cols

x_train_encode = pd.DataFrame(
    np.hstack((
        x_train[num_cols].values,
        x_train_new
    )),
    columns=all_cols
)
x_test_encode = pd.DataFrame(
    np.hstack((
        x_test[num_cols].values,
        x_test_new
    )),
    columns=all_cols
)

In [138]:
x_train_encode.shape

(620, 60)

In [139]:
x_test_encode.shape

(155, 60)

In [140]:
x_test_encode

,Age,Annual_Income,Sum_Assured,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Agent_Rating,...,Occupation_Housewife,Occupation_Retired,Occupation_Salaried,Occupation_Self-Employed,Occupation_Student,Policy_Type_Life,Policy_Type_Term,Policy_Type_Travel,Policy_Type_Vehicle,Auto_Renewal_Enabled_Yes
0,27.0,1480000.0,2502238.0,10.0,0.0,0.0,0.0,4.0,2.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,67.0,1480000.0,2502238.0,9.0,0.0,0.0,0.0,0.0,6.0,3.8,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,67.0,1480000.0,2502238.0,6.0,0.0,0.0,0.0,4.0,9.0,4.5,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,42.0,1480000.0,4800000.0,8.0,0.0,0.0,0.0,4.0,5.0,3.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,31.0,1480000.0,2502238.0,0.0,2.0,0.0,0.0,0.0,1.0,2.9,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,56.0,1480000.0,2502238.0,8.0,0.0,0.0,1.0,1.0,7.0,4.4,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
151,31.0,1610000.0,1450000.0,12.0,0.0,0.0,3.0,3.0,6.0,4.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
152,60.0,440000.0,2502238.0,7.0,3.0,0.0,0.0,3.0,7.0,4.7,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
153,30.0,1480000.0,100000.0,10.0,0.0,0.0,0.0,0.0,2.0,4.5,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
154,0.0,1480000.0,2502238.0,10.0,1.0,75000.0,2.0,3.0,7.0,4.9,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [141]:
from sklearn.preprocessing import StandardScaler

In [142]:
std=StandardScaler()

In [143]:
x_train_std = pd.DataFrame(
    std.fit_transform(x_train_encode),
    columns=x_train_encode.columns,
    index=x_train_encode.index
)

In [144]:
x_train_std

,Age,Annual_Income,Sum_Assured,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Agent_Rating,...,Occupation_Housewife,Occupation_Retired,Occupation_Salaried,Occupation_Self-Employed,Occupation_Student,Policy_Type_Life,Policy_Type_Term,Policy_Type_Travel,Policy_Type_Vehicle,Auto_Renewal_Enabled_Yes
0,1.010515,0.028261,-0.007763,-1.402427,0.042137,-0.262633,-0.746130,-0.658296,-0.454805,0.760640,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.3849,-0.489898,-0.537570,2.051849,-0.482291,-0.946586
1,-0.152290,0.099198,-0.007763,-1.672209,-0.749533,-0.262633,-0.090888,-0.981962,1.223643,-0.353259,...,-0.365315,2.508808,-0.390405,-0.393144,-0.3849,-0.489898,-0.537570,-0.487365,-0.482291,-0.946586
2,1.068656,-0.432834,-0.007763,0.755823,0.042137,-0.262633,-0.746130,0.636370,0.552264,-1.467157,...,-0.365315,-0.398596,-0.390405,2.543596,-0.3849,2.041241,-0.537570,-0.487365,-0.482291,-0.946586
3,0.836095,0.028261,-0.007763,-0.053521,-0.749533,-0.262633,2.530079,-0.010963,0.216574,1.178352,...,-0.365315,2.508808,-0.390405,-0.393144,-0.3849,2.041241,-0.537570,-0.487365,-0.482291,-0.946586
4,-0.501132,0.028261,-0.007763,0.755823,-0.749533,-0.262633,-0.746130,-0.658296,1.223643,-1.327920,...,-0.365315,2.508808,-0.390405,-0.393144,-0.3849,-0.489898,-0.537570,-0.487365,-0.482291,-0.946586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,0.777954,0.028261,-0.007763,1.565166,-0.749533,-0.262633,-0.746130,2.254703,1.559333,1.456826,...,-0.365315,-0.398596,2.561440,-0.393144,-0.3849,-0.489898,-0.537570,2.051849,-0.482291,-0.946586
616,1.359357,0.028261,-0.007763,1.025604,0.042137,-0.012122,0.564353,1.283703,-1.461875,-1.745632,...,-0.365315,-0.398596,2.561440,-0.393144,-0.3849,-0.489898,1.860224,-0.487365,-0.482291,1.056428
617,1.068656,0.028261,3.131369,-0.323302,-0.749533,-0.262633,-0.746130,-0.334629,1.559333,-1.467157,...,-0.365315,2.508808,-0.390405,-0.393144,-0.3849,-0.489898,1.860224,-0.487365,-0.482291,1.056428
618,0.603534,0.028261,-0.007763,-1.672209,-0.749533,-0.262633,-0.746130,-0.981962,1.223643,-1.467157,...,2.737362,-0.398596,-0.390405,-0.393144,-0.3849,2.041241,-0.537570,-0.487365,-0.482291,-0.946586
619,0.312832,0.028261,-0.007763,-0.053521,0.833807,-0.262633,-0.090888,-0.334629,1.223643,1.178352,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.3849,-0.489898,-0.537570,2.051849,-0.482291,1.056428

In [145]:
x_test_std = pd.DataFrame(
    std.transform(x_test_encode),
    columns=x_test_encode.columns,
    index=x_test_encode.index
)

In [146]:
x_test_std

,Age,Annual_Income,Sum_Assured,Years_With_Company,Total_Claims,Claim_Amount,Late_Payment_Count,Previous_Renewals,Satisfaction_Score,Agent_Rating,...,Occupation_Housewife,Occupation_Retired,Occupation_Salaried,Occupation_Self-Employed,Occupation_Student,Policy_Type_Life,Policy_Type_Term,Policy_Type_Travel,Policy_Type_Vehicle,Auto_Renewal_Enabled_Yes
0,-1.024394,0.028261,-0.007763,1.025604,-0.749533,-0.262633,-0.746130,0.312704,-1.126185,0.342928,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.384900,-0.489898,-0.537570,2.051849,-0.482291,-0.946586
1,1.301217,0.028261,-0.007763,0.755823,-0.749533,-0.262633,-0.746130,-0.981962,0.216574,0.064453,...,2.737362,-0.398596,-0.390405,-0.393144,-0.384900,2.041241,-0.537570,-0.487365,-0.482291,1.056428
2,1.301217,0.028261,-0.007763,-0.053521,-0.749533,-0.262633,-0.746130,0.312704,1.223643,1.039115,...,-0.365315,-0.398596,-0.390405,-0.393144,2.598076,-0.489898,1.860224,-0.487365,-0.482291,-0.946586
3,-0.152290,0.028261,3.430653,0.486041,-0.749533,-0.262633,-0.746130,0.312704,-0.119116,-0.074784,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.384900,-0.489898,-0.537570,2.051849,-0.482291,-0.946586
4,-0.791833,0.028261,-0.007763,-1.672209,0.833807,-0.262633,-0.746130,-0.981962,-1.461875,-1.188682,...,-0.365315,2.508808,-0.390405,-0.393144,-0.384900,-0.489898,-0.537570,2.051849,-0.482291,1.056428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.661674,0.028261,-0.007763,0.486041,-0.749533,-0.262633,-0.090888,-0.658296,0.552264,0.899877,...,-0.365315,2.508808,-0.390405,-0.393144,-0.384900,2.041241,-0.537570,-0.487365,-0.482291,1.056428
151,-0.791833,0.489356,-1.582353,1.565166,-0.749533,-0.262633,1.219595,-0.010963,0.216574,1.596064,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.384900,-0.489898,-0.537570,-0.487365,-0.482291,1.056428
152,0.894235,-3.660500,-0.007763,0.216260,1.625477,-0.262633,-0.746130,-0.010963,0.552264,1.317589,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.384900,-0.489898,1.860224,-0.487365,-0.482291,-0.946586
153,-0.849973,0.028261,-3.602520,1.025604,-0.749533,-0.262633,-0.746130,-0.981962,-1.126185,1.039115,...,-0.365315,-0.398596,2.561440,-0.393144,-0.384900,-0.489898,1.860224,-0.487365,-0.482291,1.056428
154,-2.594181,0.028261,-0.007763,1.025604,0.042137,1.616202,0.564353,-0.010963,0.552264,1.596064,...,-0.365315,-0.398596,-0.390405,-0.393144,-0.384900,-0.489898,1.860224,-0.487365,-0.482291,-0.946586

In [147]:
# target coloum encode

In [148]:
lb=LabelEncoder()

In [149]:
y_train

133    Not Renewed
753    Not Renewed
55         Renewed
405        Renewed
673        Renewed
          ...
71         Renewed
106    Not Renewed
270        Renewed
435        Renewed
102        Renewed
Name: Renewal_Status_Next_Year, Length: 620, dtype: object

In [150]:
lb.fit(y_train)

LabelEncoder()

In [151]:
lb.classes_

array(['Not Renewed', 'Renewed'], dtype=object)

In [152]:
y_train = pd.DataFrame(
    lb.transform(y_train),
    columns=["Renewal_Status_Next_Year"],
    index=y_train.index
)

y_test = pd.DataFrame(
    lb.transform(y_test),
    columns=["Renewal_Status_Next_Year"],
    index=y_test.index
)

In [153]:
y_train

     Renewal_Status_Next_Year
133                         0
753                         0
55                          1
405                         1
673                         1
..                        ...
71                          1
106                         0
270                         1
435                         1
102                         1

[620 rows x 1 columns]

In [154]:
x_train_std.shape

(620, 60)

In [155]:
y_train.shape

(620, 1)

In [156]:
x_test_std.shape

(155, 60)

In [157]:
y_test.shape

(155, 1)

In [158]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

In [160]:
rf.fit(x_train_std,y_train)

RandomForestClassifier(max_depth=10, n_estimators=300, random_state=42)

In [162]:
y_pre=rf.predict(x_test_std)

In [163]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [165]:
accuracy_score(y_test,y_pre)*100

73.54838709677419

In [167]:
rf.score(x_train_std,y_train)*100

99.51612903225806

In [168]:
rf.score(x_test_std,y_test)*100

73.54838709677419

In [169]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

rf.fit(x_train_std, y_train)

y_pred = rf.predict(x_test_std)

from sklearn.metrics import accuracy_score

print("Train:", rf.score(x_train_std, y_train)*100)
print("Test :", rf.score(x_test_std, y_test)*100)

Train: 80.80645161290323
Test : 78.06451612903226

In [ ]:
accuracy_score(x_t)